[workspace]
resolver = "3"
members = [
    "crates/fm-core",
    "crates/fm-cli",
    "crates/fm-tui",
    "crates/fm",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
clap = { version = "4.6.7", features = ["derive"] }
ratatui = "0.30.2"
tempfile = "3.27.0"
fm-core = { path = "crates/fm-core" }
fm-cli = { path = "crates/fm-cli" }
fm-tui = { path = "crates/fm-tui" }