[workspace]
resolver = "3"
members = [
    "crates/pfad_core",
    "crates/pfad_cli",
    "crates/pfad_tui",
    "crates/pfad",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
clap = { version = "4.6.7", features = ["derive"] }
ratatui = "0.30.2"
tempfile = "3.27.0"
pfad_core = { path = "crates/pfad_core" }
pfad_cli = { path = "crates/pfad_cli" }
pfad_tui = { path = "crates/pfad_tui" }